### ISSUE TITLE
Call PTA application from non-secure world

### ISSUE THREAD

**Issue by PratikGajera** [OP-TEE/optee_os#3122]
Hi Team,

I want to call PTA (pseudo trusted application) which is inside in optee (core/arch/arm/pta/) from non-secure world. As per my understanding, I need to write only host application like optee_examples (https://github.com/linaro-swg/optee_examples).
If my understanding is not clear, then please suggest me from scratch, How to call PTA application from non-secure world?

For example,  stats PTA application(core/arch/arm/pta/stat.c)

Thanks,
Pratik GAJERA

**Comment by jforissier** [comment]
Hi @PratikGajera ,

PTA are invoked the same way as normal TAs. For the stats PTA, there is example client code in `xtest`: https://github.com/OP-TEE/optee_test/blob/master/host/xtest/stats.c

**Comment by PratikGajera** [comment]
@jforissier, Thanks for providing example. 
Enabled stats PTA application using CFG_WITH_STATS=y from OPTEE. I am trying to execute Host application (https://github.com/OP-TEE/optee_test/blob/master/host/xtest/stats.c) as you suggested from normal-world. But, it is giving error **"optee_example_stats: TEEC_OpenSession: res 0xffff0008 err_orig 0x3"**. Also, I checked hello_world Host and TA application from normal world, that is working fine very well.
Please suggest me if something missing here.

**Comment by PratikGajera** [comment]
Gentle reminder!

**Comment by jbech-linaro** [comment]
> Gentle reminder!

FYI, most of the core team (@jforissier included) is on summer vacation and will be so for ~2 weeks more at least. But to give some support I just did this exercise myself with PTA when I implemented support for the derive unique TA stuff. You'll see a pretty clean example here

https://github.com/OP-TEE/optee_test/blob/40aacb6dc33bbf6ee329f40274bfe7bb438bbf53/ta/crypt/derive_key_taf.c#L25-L45

showing how I invoke a PTA from another TA. That is enabled by default, i.e., there is no need to enable any flags if you want to check that out. All that is invoked from "xtest 4013". But as @jforissier already said, you invoke PTA's the same way as for User TA's.

**Comment by PratikGajera** [comment]
@jbech-linaro thanks for providing a example. I executed this demo example and result is, Host application call TA application and TA application call PTA application. But somewhere os is hangout and need to reboot again. So, I want to see debug and info log from OPTEE. But, I can't see optee logs on UART console after setting CFG_TEE_TA_LOG_LEVEL=4.

**Comment by jbech-linaro** [comment]
@PratikGajera , since this is is a PTA it's running in kernel context, therefore you need to enable `CFG_TEE_CORE_LOG_LEVEL=<1, ..., 4>` also to be able to see all debug info in the UART. Btw, this particular functionality is being tested by xtest, so I'm a bit surprised when you're saying that it hangs?

**Comment by PratikGajera** [comment]
Now, PTA application is working fine in order to change optee revision (146a256b264a275a5930efa3989205b04216e984), but. I can't still see optee debug log on my console after setting CFG_TEE_CORE_LOG_LEVEL=4. Even, OPTEE boot up log is printed on UART console at board boot up time only.

**Comment by jbech-linaro** [comment]
> but. I can't still see optee debug log on my console after setting CFG_TEE_CORE_LOG_LEVEL=4.

Can you give it a try using QEMU, just so you have a known starting point that should work?
