### ISSUE TITLE
-Werror=unused-variable: Can't Build OP-TEE

### ISSUE THREAD

**Issue by lordqwerty** [OP-TEE/optee_os#550]
Hello, 

I get the following compilation error when building OP-TEE:
```
  CC    disas/arm.o
  CXX   disas/arm-a64.o
In file included from /home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/disasm-a64.h:32:0,
                 from disas/arm-a64.cc:20:
/home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h:98:13: error: ‘vixl::kFP32PositiveInfinity’ defined but not used [-Werror=unused-variable]
 const float kFP32PositiveInfinity = rawbits_to_float(0x7f800000);
             ^
/home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h:99:13: error: ‘vixl::kFP32NegativeInfinity’ defined but not used [-Werror=unused-variable]
 const float kFP32NegativeInfinity = rawbits_to_float(0xff800000);
             ^
/home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h:100:14: error: ‘vixl::kFP64PositiveInfinity’ defined but not used [-Werror=unused-variable]
 const double kFP64PositiveInfinity =
              ^
/home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h:102:14: error: ‘vixl::kFP64NegativeInfinity’ defined but not used [-Werror=unused-variable]
 const double kFP64NegativeInfinity =
              ^
/home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h:107:21: error: ‘vixl::kFP64SignallingNaN’ defined but not used [-Werror=unused-variable]
 static const double kFP64SignallingNaN =
                     ^
/home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h:109:20: error: ‘vixl::kFP32SignallingNaN’ defined but not used [-Werror=unused-variable]
 static const float kFP32SignallingNaN = rawbits_to_float(0x7f800001);
                    ^
/home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h:112:21: error: ‘vixl::kFP64QuietNaN’ defined but not used [-Werror=unused-variable]
 static const double kFP64QuietNaN =
                     ^
/home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h:114:20: error: ‘vixl::kFP32QuietNaN’ defined but not used [-Werror=unused-variable]
 static const float kFP32QuietNaN = rawbits_to_float(0x7fc00001);
                    ^
/home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h:117:21: error: ‘vixl::kFP64DefaultNaN’ defined but not used [-Werror=unused-variable]
 static const double kFP64DefaultNaN =
                     ^
/home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h:119:20: error: ‘vixl::kFP32DefaultNaN’ defined but not used [-Werror=unused-variable]
 static const float kFP32DefaultNaN = rawbits_to_float(0x7fc00000);
                    ^
cc1plus: all warnings being treated as errors
/home/jorden/devel/optee/dev/qemu/rules.mak:94: recipe for target 'disas/arm-a64.o' failed
make[1]: *** [disas/arm-a64.o] Error 1
make[1]: Leaving directory '/home/jorden/devel/optee/dev/qemu'
Makefile:60: recipe for target 'qemu' failed
make: *** [qemu] Error 2
```

I used the `repo` tool and have tried both the `default.xml` and `default_stable.xml` (for QEMU) and in both cases I get the same compilation error. Is there a reason why these variables are here if `unused-variable` is not allowed? 

Any help would be much appreciated.

**Comment by vchong** [comment]
Did you make changes to try to specify 64-bit builds? The qemu build is 32-bit only.

**Comment by lordqwerty** [comment]
I have not deviated from the build instructions as specified in the [README](https://github.com/OP-TEE/optee_os/blob/master/README.md). 

If this is the case where do I need to define it to build with 32-bit only?

**Comment by vchong** [comment]
That's good. You don't have to define anything. Make sure you have the latest for all the repos?

**Comment by lordqwerty** [comment]
Yup I have all changes by running `repo sync`. I also have tried to do this in a fresh Ubuntu VM and also get the same error. 

Any ideas?

**Comment by vchong** [comment]
Lemme try a build tomorrow to see if there's a bug.
In the meantime, I think you can remove the variables in question.
Ref: https://lists.gnu.org/archive/html/qemu-devel/2014-10/msg01017.html

**Comment by vchong** [comment]
I didn't encounter this error in my build.

```
  CC    block/backup.o
  CC    disas/arm.o
  CXX   disas/arm-a64.o
  CC    disas/i386.o
  CXX   disas/libvixl/utils.o
  CXX   disas/libvixl/a64/instructions-a64.o
  CXX   disas/libvixl/a64/decoder-a64.o
  CXX   disas/libvixl/a64/disasm-a64.o
  CC    fsdev/qemu-fsdev.o
```

Something must be off with your environment or setup. Do you maybe have ```-Werror=unused-variable``` set in the environment somewhere and applied to the build by accident? I can't seem to find this setting in my build. Can you include the exacts commands you used from the beginning to this point? Also include the full build log for /home/jorden/devel/optee/dev/qemu?

**Comment by lordqwerty** [comment]
I tested mine on a fresh VM following the instructions. Perhaps the instructions are missing something?

**Comment by vchong** [comment]
What's your VM? Does the output of ```gcc -v``` give you version 5 or higher? If yes, try using gcc lower than version 5. Alternately, just remove the unused variable as mentioned above and try compiling again, i.e. remove /home/jorden/devel/optee/dev/qemu/disas/libvixl/a64/instructions-a64.h lines 98-121 (patch below) and run ```make all``` again.

```
---
 disas/libvixl/a64/instructions-a64.h | 24 ------------------------
 1 file changed, 24 deletions(-)

diff --git a/disas/libvixl/a64/instructions-a64.h 
b/disas/libvixl/a64/instructions-a64.h
index d5b90c5..1eea851 100644
--- a/disas/libvixl/a64/instructions-a64.h
+++ b/disas/libvixl/a64/instructions-a64.h
@@ -95,30 +95,6 @@ const unsigned kDoubleExponentBits = 11;
 const unsigned kFloatMantissaBits = 23;
 const unsigned kFloatExponentBits = 8;
 
-const float kFP32PositiveInfinity = rawbits_to_float(0x7f800000);
-const float kFP32NegativeInfinity = rawbits_to_float(0xff800000);
-const double kFP64PositiveInfinity =
-    rawbits_to_double(UINT64_C(0x7ff0000000000000));
-const double kFP64NegativeInfinity =
-    rawbits_to_double(UINT64_C(0xfff0000000000000));
-
-// This value is a signalling NaN as both a double and as a float (taking the
-// least-significant word).
-static const double kFP64SignallingNaN =
-    rawbits_to_double(UINT64_C(0x7ff000007f800001));
-static const float kFP32SignallingNaN = rawbits_to_float(0x7f800001);
-
-// A similar value, but as a quiet NaN.
-static const double kFP64QuietNaN =
-    rawbits_to_double(UINT64_C(0x7ff800007fc00001));
-static const float kFP32QuietNaN = rawbits_to_float(0x7fc00001);
-
-// The default NaN values (for FPCR.DN=1).
-static const double kFP64DefaultNaN =
-    rawbits_to_double(UINT64_C(0x7ff8000000000000));
-static const float kFP32DefaultNaN = rawbits_to_float(0x7fc00000);
-
-
 enum LSDataSize {
   LSByte        = 0,
   LSHalfword    = 1,
-- 
```

**Comment by lordqwerty** [comment]
Managed to solve the issue with the help of druff from IRC channel. I am running a recent version of `gcc` so the build errors. It can be fixed by changing [qemu.mk](https://github.com/OP-TEE/build/blob/master/qemu.mk#L60) on line 60 at the end you can add `--extra-cflags="-Wno-error"`. 

Complete it looks like:

```
qemu:
	cd $(QEMU_PATH); ./configure --target-list=arm-softmmu --cc="$(CCACHE)gcc" --extra-cflags="-Wno-error"
	$(MAKE) -C $(QEMU_PATH)
```

Happy for this to be closed but might be worth documenting it. I am happy to update the README to do this, if you think it is worth doing. 

Thanks for all your help, I really appreciate it.

**Comment by vchong** [comment]
@lordqwerty Ok. Glad you have it resolved.

@jbech-linaro We should probably patch this. Would you prefer back-porting 94cc44a9e51ea from qemu master, or just adding the flag above to the makefile? Probably safer to just add the flag?

**Comment by lordqwerty** [comment]
You beat me to it. I'll close mine off and keep yours. 

Cheers!

**Comment by vchong** [comment]
Actually that was just for my own fork. Please ask druff first if he wants to do it since it's his patch. If he doesn't, then just reopen yours.

**Comment by jbech-linaro** [comment]
@pm215 what is your suggestion here, usually I'm a bit reluctant to adding flags that just are suppressing warnings (and/or errors).

**Comment by pm215** [comment]
This issue is fixed in upstream libVIXL, and also in upstream QEMU (by our pulling in a new libvixl). If you want an instant fix you could cherry-pick QEMU commit 94cc44a9e51eabd6 (which is where we temporarily fixed it locally before we moved to the newer libvixl). Or you could stick with the -Wno-error fix for the moment until you update to a proper upstream QEMU (which we should be able to do around the end of the year or early next year once QEMU 2.5 has released and the necessary TrustZone patches can land in QEMU trunk).

**Comment by vchong** [comment]
Cherry-picking 94cc44a9e51eabd6 helps fix this error, but it'll just bring us to the next warning/error below.

```hw/virtio/virtio-rng.c:150:31: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]  if (!vrng->conf.period_ms > 0) {```
(ref https://irclogs.linaro.org/2015/11/18/%23linaro-security.html)

which seems to be fixed by https://github.com/qemu/qemu/commit/a3a292c420d2fec3c07a7ca56fbb064cd57a298a, but this might be an endless loop, so if we can update to a proper upstream QEMU soon, adding the flag seems like a better option?

**Comment by jbech-linaro** [comment]
Ok, thanks @pm215 and @vchong for your feedback. Let's merge the `-Wno-error` fix and use that until we switch to the proper QEMU repo soon.

**Comment by pm215** [comment]
Incidentally, the QEMU approach to -Werror is that we enable it only for builds from git; for release tarballs (as used by end users) configure will automatically select a --disable-werror build. The idea is that we can catch warnings as developers but don't unnecessarily induce build failures for users. So if OP-TEE thinks of QEMU as just a third-party bit of code it doesn't care about making changes to, it might be better to configure it with --disable-werror anyway.

**Comment by lordqwerty** [comment]
https://github.com/OP-TEE/build/pull/26 has been merged. Can close issue but the `default_stable.xml` will still fail as it is at tag 1.0.1. 

@jbech-linaro Should a tag 1.0.1-rc1 be made for this change and the manifest updated? Alternatively specify the commit 4b630426c9fdea0981b93028004c7a6f840348d7 in the revision as an interim solution until the QEMU 2.5 release as mentioned by @pm215 

I will leave the issue open, but please close issue if you feel this is not relevant.

**Comment by jbech-optee-adm** [comment]
Patch has been merged, closing this issue.
